name: npm ci

on:
  push:
    tags:
      - '*'
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    needs: [test, eslint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Download test results
        uses: actions/download-artifact@v2
        with:
          name: test-results
          path: coverage/

      - name: Install dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Publish to npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish

